# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54997f96902a88aa85de643fed38b1a7760ebbe480cf8f6333a4d053d3bc5c0d3d54e091484754945c1a9b57231d9c714c04a708cf0675a3ac14ba1eb9945d8a

test:
  secret_key_base: d0b3386abf1e87188d185d0e77bf0ba61a40a2d792ffffba92e6c07c04ab5f986fd499c2ea86174f97a205108980a2987054fce47a93fa38d4abe550f7fc9a3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
